### PR TITLE
feat(working): Add the "Go to top" button on the Landing Page

### PR DESCRIPTION
**Pull request by Vooxify**
I think I'm a bad developer, but you can always **check out** my code. I've added a 'return to top' button for the landing page. I've also changed the colors of the navigation bar for the light theme and I've added the '--adjustable-monochrome' allows the shadow effect without having to worry about the color. Let me know if this is acceptable.

https://github.com/Magic-Fishes/Ecole-Directe-Plus/assets/128456121/6d585351-07ee-4227-8373-31dc0e5875d5

### CODE REVIEW

**Comment by Truiteseche** [comment]
Very nice-looking animation, congrats! Please can you just rename the variable `--text-color-alt-0` back to `--text-color-alt` as this will surely create conflicts with upcoming commits and incoming pull requests. Thanks for your contribution, I will merge after this change if you think you're done.

**Comment by Truiteseche** [comment]
Nicely done, thanks

**Comment by Fefedu973** [comment]
The merge just blow the landing page up, it's not working anymore ):

**Comment by Truiteseche** [comment]
> The merge just blow the landing page up, it's not working anymore ):

Indeed, i'm working on fixing that ;)

**Comment by Fefedu973** [comment]
Nice !

**Pull request merged**
