### PR TITLE
Launcher Dor Ecole DIrecte Plus

### PR DESCRIPTION
**Pull request by danbenba**
Adding Launcher for launch easy

### CODE REVIEW

**Comment by OeildeLynx31** [comment]
You should also add a .sh file for Linux operating systems

**Review by xav35000 — CHANGES_REQUESTED** [review]
Should be in a separate repo/do not really need to exist @Truiteseche can you look into this

**Comment by xav35000** [comment]
This would more useful with something like this : 

`NET SESSION >nul 2>&1
IF %ERRORLEVEL% NEQ 0 (
	echo This setup needs admin permissions. Please run this file as admin.
	pause
	exit
)

set NODE_VER=null
set NODE_EXEC=node-v0.8.11-x86.msi
set SETUP_DIR=%CD%
node -v >tmp.txt
set /p NODE_VER=<tmp.txt
del tmp.txt
IF %NODE_VER% NEQ null (
	echo INSTALLING node ...
	mkdir tmp
	IF NOT EXIST tmp/%NODE_EXEC% (
		echo Node setup file does not exist. Downloading ...
		cd ../bin
		START /WAIT wget http://nodejs.org/dist/v0.8.11/%NODE_EXEC%
		move %NODE_EXEC% %SETUP_DIR%/tmp
	)
	cd %SETUP_DIR%/tmp
	START /WAIT %NODE_EXEC%
	cd %SETUP_DIR%
) ELSE (
	echo Node is already installed. Proceeding ...
)
`

**Comment by Truiteseche** [comment]
Might be cool to also make sure that all dependencies are installed
Just need to add a simple `npm install` after installing nodejs

**Comment by xav35000** [comment]
Please update or close the PR @danbenba

**Comment by danbenba** [comment]
> Please update or close the PR @danbenba 

Vous pouvez collaborer. Et donner moi le code je le modifierai

**Comment by xav35000** [comment]
I do not have time nor the desire to edit this code to a useful state and i think we don't really need it, if nobody update this until
the 09/06/24, the pr will be closed.

**Pull request closed without merging**
