### PR TITLE
Update Grades.jsx

### PR DESCRIPTION
**Pull request by Super-Code774**
1. Reduce redundancy by merging `userData.get("activePeriod")` and `userData.set("activePeriod", selectedPeriod)` calls into a single function
2. Use a callback function to avoid side effects when removing the component
3. Remove unnecessary spaces in JSX tags to improve readability
4. Rename variables to be more descriptive
5. Clean up unnecessary or redundant comments
6. Add "alt" attributes to images to improve accessibility
7. Add "key" property to list items to improve rendering performance
8. Use constants for strings used multiple times

### CODE REVIEW

**Comment by Ewalwi** [comment]
Is it finished ?

**Comment by Fefedu973** [comment]
test

**Comment by Super-Code774** [comment]
The code yes but i never test it

**Comment by Ewalwi** [comment]
well, okay, I request saumon to review it

**Comment by Super-Code774** [comment]
Thanks

**Comment by saumon-brule** [comment]
Bro you cannot just refactor the code and change the indentation size and then claim that you did an *upgrade of Grades.jsx*.
Also stuff like :
> Add "alt" attributes to images to improve accessibility
> Add "key" property to list items to improve rendering performance
There is no images neither rendered array in the Grades.jsx file

**Pull request closed without merging**
