### PR TITLE
Added the ability to see homeworks for any days AND display class average for each perdiod

### PR DESCRIPTION
**Pull request by Fefedu973**
Added the ability to see homeworks for any days using a manual switch, you can see your homeworks of any days. Now you are automatically redirected to the current day for homeworks

### CODE REVIEW

**Comment by Fefedu973** [comment]
This is just a vey early implementation. it needs a lot of updates to be good for merge

**Comment by Fefedu973** [comment]
ADDED: display class average for each perdiod
(potential issue if this is disabled by the high-school. Should display N/A but it is maybe better to disable the tooltip entirely)

**Comment by xav35000** [comment]
I think it is better to simply disable the tooltip.

Is your PR complete or do you want to add other things ?

**Comment by Fefedu973** [comment]
> I think it is better to simply disable the tooltip.
> 
> Is your PR complete or do you want to add other things ?

Idk if it is "complete" there are a lot of things to fix before merge but what do you want to do with the tooltip I don't understand?

**Comment by xav35000** [comment]
>  it is maybe better to disable the tooltip entirely

If the school disabled the class average, I think that hiding the tooltip entirely is better than displaying N/A

**Comment by Fefedu973** [comment]
Je vais fermer cette pull request en faveur d'une autre dans la branche working où les modifications nécessaires ont été apportées et où à la place du toggle dégueulasse j'ai ajouté un calendrier pour les devoirs

**Pull request closed without merging**
