### PR TITLE
Christmas design

### PR DESCRIPTION
**Pull request by Ewalwi**
Designed the christmas theme of this year...
Added snow effects as snowfall or snowy elements, and lighting garland
Added a new setting: periodEvent, aiming to set up faster future themes that could be added
Finally, the christmas theme is applied only if the PartyMode is enabled and the new setting periodEvent is defined as 'christmas'

### CODE REVIEW

**Comment by Fefedu973** [comment]
Je propose d'ajouter height:100% à .lightrope pour éviter que la guirlande sois coupée
Il faudrait fix le fait que l'effet neige soit coupé au scroll
Sur les windows header ça serait cool si l'effet neige pouvait ressembler à un truc comme ça.
Sinon c'est génial comme initiative merci!
image

**Comment by Fefedu973** [comment]
[Ecole-Directe-Plus-christmas-design.zip](https://github.com/user-attachments/files/17781131/Ecole-Directe-Plus-christmas-design.zip)
J'ai ajouté le haut en neige je trouve ça pas mal mais ça mériterait quelques ajustements. Je te laisse voir
image

**Comment by M6a5x98** [comment]
Stylé !

**Comment by Fefedu973** [comment]
[Ecole-Directe-Plus-christmas-design.zip](https://github.com/user-attachments/files/17784607/Ecole-Directe-Plus-christmas-design.zip)
Voici une meilleure version (à implémenter avec tes changements)

**Comment by FuiboHawks** [comment]
Hi Everyone ! I am new and I have been using your "upgrade" of Ecole Directe that is just very basic and boring. But, do you think it's possible to add the "Espace de Travail" part of the normal Ecole Directe ? Thx

**Comment by FuiboHawks** [comment]
Ok thanks i will join it

**Comment by FuiboHawks** [comment]
That's it thanks @Ewalwi

**Comment by Ewalwi** [comment]
you welcome, don't hesitate if u need something else

**Comment by FuiboHawks** [comment]
ok

**Comment by Ewalwi** [comment]
@Truiteseche that's done, after the merge, the design will automatically start the 1st of december and stop the 31th 😎😎😎

**Comment by Ewalwi** [comment]
missing saumon's recommendations... On it !

**Comment by Ewalwi** [comment]
code is now very clean 👍 and the update conflicts are now..... dodged 😂 The design will auto. start the 1st and stop the 31st

**Comment by Fefedu973** [comment]
?

**Comment by Ewalwi** [comment]
bug de rename

**Comment by Ewalwi** [comment]
reopening

**Pull request closed without merging**
